---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1tvdj80rd99ct9xvcw9p27pk4pyu74xt69dgk40qd7g3jwv29madqqvry8f"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1tvdj80rd99ct9xvcw9p27pk4pyu74xt69dgk40qd7g3jwv29madqqvry8f"
stores:
  yaml:
    indent: 2
