# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mQ6+LmUdpsq0HZdGhZoGfiOl6OVe78JnXxyY/THBUsPJR++pV4qEiA==,iv:kRIcL+eKHeBPwxqe4fbfDeh5DNoXdRe+E5t4sxiGWG8=,tag:o1itEXT6EwEoYLgQziOBRA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tvdj80rd99ct9xvcw9p27pk4pyu74xt69dgk40qd7g3jwv29madqqvry8f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSVVVbnNuVWFwZEttdW85
        SnNKOTlKWStxTloxWEdSUnRMZEFQRGlJcVIwClRhQXlrZW5FZnQ3Nitseld1Q0RF
        bXRhQUFxRnlsM0IybkhMY2VlYnBFbzQKLS0tIHdDNFNLTkY2T0gwMytDaE56cEtP
        ZFg5S3BOTzh2VElqSjRlM2lsYkQrUWcKDDLXSUGDVVLUzSTR7vnlIyUp1b2nOJrx
        6I5hoAvWgz0hjzySaEVzbt+ChTnFhqzG33cdCEH1tf/2obq0T0z/Hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T22:36:02Z"
  mac: ENC[AES256_GCM,data:x3Uu4hDC5biV3h1zuGO2g2aYsFqXjtZW4UOUd49dRaD65uJDwzrNU8pqUeSlH6ovbrWO90Tp3lANxy9K1E9KHKdcKK7R2+UdYu2TUGYqcwQ+T7W6mLT86NkyMUyq7/FKO4WmI20VBH/4Wx0ERlZWdgVt5p9IjGb00AbTUR8sraY=,iv:tb1lQHSNaR6N6B+KY2Ibsq/CaDR+1qqxRCLtcoj8pvU=,tag:8tv9nTAK2OGJ/UaNzI+2Bg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
